name: ci

on:
  push:
    branches: [ 'master', 'main' ]
  pull_request:
    branches: [ 'master', 'main' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore
      run: dotnet restore College.Domain/College.Domain.csproj && dotnet restore College.MVC/College.MVC.csproj && dotnet restore College.Tests/College.Tests.csproj
    - name: Build (Release)
      run: dotnet build College.Domain/College.Domain.csproj --configuration Release --no-restore && dotnet build College.MVC/College.MVC.csproj --configuration Release --no-restore && dotnet build College.Tests/College.Tests.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test College.Tests/College.Tests.csproj --configuration Release --no-build --verbosity normal
